apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{- include "smart-supply.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "smart-supply.componentSelector" (dict "Release" .Release "Values" .Values "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "smart-supply.componentSelector" (dict "Release" .Release "Values" .Values "component" "frontend") | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: {{ include "smart-supply.image" (dict "Values" .Values "repository" .Values.frontend.image.repository) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - { name: http, containerPort: 80 }
          resources: {{- toYaml .Values.frontend.resources | nindent 12 }}
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{- include "smart-supply.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "smart-supply.componentSelector" (dict "Release" .Release "Values" .Values "component" "frontend") | nindent 4 }}
  ports:
    - { name: http, port: {{ .Values.frontend.service.port }}, targetPort: http }
